const species = [
	{ icon: '🐒', name: 'Affe', group: 'Primaten' },
	{ icon: '🦍', name: 'Gorilla', group: 'Primaten' },
	{ icon: '🐕', name: 'Hund', group: 'Canide' },
	{ icon: '🐩', name: 'Pudel', group: 'Canide' },
	{ icon: '🐺', name: 'Wolf', group: 'Canide' },
	{ icon: '🦊', name: 'Fuchs' },
	{ icon: '🦝', name: 'Waschbär', group: 'Ursidae' },
	{ icon: '🐈', name: 'Katze', group: 'Felidae' },
	{ icon: '🦁', name: 'Löwe', group: 'Felidae' },
	{ icon: '🐯', name: 'Tiger', group: 'Felidae' },
	{ icon: '🐆', name: 'Leopard', group: 'Felidae' },
	{ icon: '🐎', name: 'Pferd', group: 'Equidae' },
	{ icon: '🦄', name: 'Einhorn', group: 'Equidae' },
	{ icon: '🦓', name: 'Zebra', group: 'Equidae' },
	{ icon: '🦌', name: 'Reh' },
	{ icon: '🐂', name: 'Ochse', group: 'Bovidae' },
	{ icon: '🐃', name: 'Büffel', group: 'Bovidae' },
	{ icon: '🐄', name: 'Kuh', group: 'Bovidae' },
	{ icon: '🐖', name: 'Schwein' },
	{ icon: '🐗', name: 'Wildschwein', group: 'Bovidae' },
	{ icon: '🐏', name: 'Bock', group: 'Bovidae' },
	{ icon: '🐑', name: 'Schaf', group: 'Bovidae' },
	{ icon: '🐐', name: 'Ziege', group: 'Bovidae' },
	{ icon: '🐪', name: 'Kamel' },
	{ icon: '🦙', name: 'Lama' },
	{ icon: '🦒', name: 'Giraffe' },
	{ icon: '🐘', name: 'Elefant' },
	{ icon: '🦏', name: 'Rhinozeros' },
	{ icon: '🐁', name: 'Maus', group: 'Muroidea' },
	{ icon: '🐀', name: 'Ratte', group: 'Muroidea' },
	{ icon: '🐹', name: 'Hamster', group: 'Muroidea' },
	{ icon: '🐇', name: 'Hase' },
	{ icon: '🐿️', name: 'Eichhörnchen' },
	{ icon: '🦔', name: 'Igel' },
	{ icon: '🦇', name: 'Fledermaus' },
	{ icon: '🐻', name: 'Bär', group: 'Ursidae' },
	{ icon: '🐨', name: 'Koala' },
	{ icon: '🐼', name: 'Panda' },
	{ icon: '🦥', name: 'Faultier' },
	{ icon: '🦦', name: 'Otter' },
	{ icon: '🦨', name: 'Stinktier' },
	{ icon: '🦘', name: 'Känguruh' },
	{ icon: '🦡', name: 'Dachs' },
	{ icon: '🦃', name: 'Truthahn' },
	{ icon: '🐔', name: 'Huhn', group: 'Aves' },
	{ icon: '🐓', name: 'Gans', group: 'Aves' },
	{ icon: '🐦', name: 'Vogel', group: 'Aves' },
	{ icon: '🐧', name: 'Pinguin', group: 'Aves' },
	{ icon: '🕊️', name: 'Taube', group: 'Aves' },
	{ icon: '🦅', name: 'Adler', group: 'Aves' },
	{ icon: '🦆', name: 'Ente', group: 'Aves' },
	{ icon: '🦢', name: 'Schwan', group: 'Aves' },
	{ icon: '🦉', name: 'Eule', group: 'Aves' },
	{ icon: '🦩', name: 'Flamingo', group: 'Aves' },
	{ icon: '🦚', name: 'Pfau', group: 'Aves' },
	{ icon: '🦜', name: 'Papagei', group: 'Aves' },
	{ icon: '🐸', name: 'Frosch', group: 'Amphibien' },
	{ icon: '🐊', name: 'Krokodil', group: 'Reptilien' },
	{ icon: '🐢', name: 'Schildkröte', group: 'Reptilien' },
	{ icon: '🦎', name: 'Eidechse', group: 'Reptilien' },
	{ icon: '🐍', name: 'Schlange', group: 'Reptilien' },
	{ icon: '🐲', name: 'Drache', group: 'Reptilien' },
	{ icon: '🦕', name: 'Dinosaurier', group: 'Reptilien' },
	{ icon: '🐋', name: 'Wal', group: 'Piscis' },
	{ icon: '🐬', name: 'Delphin', group: 'Piscis' },
	{ icon: '🐟', name: 'Fisch', group: 'Piscis' },
	{ icon: '🦈', name: 'Hai', group: 'Piscis' },
	{ icon: '🐙', name: 'Oktupus', group: 'Piscis' },
	{ icon: '🐌', name: 'Schnecke' },
	{ icon: '🦋', name: 'Schmetterling', group: 'Insecta' },
	{ icon: '🐛', name: 'Raupe', group: 'Insecta' },
	{ icon: '🐜', name: 'Ameise', group: 'Insecta' },
	{ icon: '🐝', name: 'Biene', group: 'Insecta' },
	{ icon: '🐞', name: 'Marienkäfer', group: 'Insecta' },
	{ icon: '🦗', name: 'Grille', group: 'Insecta' },
	{ icon: '🕷️', name: 'Spinne' },
	{ icon: '🦂', name: 'Skorpion', group: 'Insecta' },
	{ icon: '🦟', name: 'Mosquito', group: 'Insecta' },
]
export default species
